# Generated by Django 2.2.5 on 2019-10-22 18:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/')),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('origPrice', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('inStock', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='None/<django.db.models.fields.CharField>/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProdMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='None/')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Prod')),
            ],
        ),
        migrations.AddField(
            model_name='prod',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.SubCategory'),
        ),
    ]
