# Generated by Django 2.2.5 on 2019-10-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='keywords',
            field=models.TextField(default='<ckeditor.fields.RichTextField><django.db.models.fields.CharField>'),
        ),
    ]
