# Generated by Django 2.2.5 on 2019-10-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191023_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='discount',
            field=models.FloatField(default=10.0),
        ),
    ]
