# Generated by Django 2.2.5 on 2019-10-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191027_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
