# Generated by Django 2.2.5 on 2019-11-01 11:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_prod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='keywords',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
