# Generated by Django 2.2 on 2019-11-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191101_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
