# Generated by Django 2.2.5 on 2020-05-04 19:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_requestprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='prod',
            name='detail',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='requestprod',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
