# Generated by Django 2.2.5 on 2019-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191023_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
