# Generated by Django 2.2.5 on 2019-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agent_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
