# Generated by Django 2.2.5 on 2019-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartprod_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='agentMoney',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
