# Generated by Django 2.2.5 on 2019-10-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_agentmoney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='agentMoney',
            new_name='agentEarn',
        ),
    ]
