# Generated by Django 2.2.5 on 2019-11-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agent_phonenumber'),
        ('cart', '0006_auto_20191031_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('isPaid', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Agent')),
            ],
        ),
    ]
