# Generated by Django 2.2.5 on 2019-11-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_agentearn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.AgentEarn'),
        ),
    ]
