# Generated by Django 2.2 on 2019-11-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20191101_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='agentEarn',
            field=models.FloatField(default=0),
        ),
    ]
