# Generated by Django 2.2 on 2019-11-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20191106_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='agentEarn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
